---
title: "Mi portfolio"
author: "Manuel Torres Acosta"
output: 
  html_document: 
    df_print: kable
    toc: TRUE
    toc_depth: 4
---

<link rel="stylesheet" href="style.css">

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
```

<br>

En éste documento se pueden visualizar algunos de los proyectos que he realizado durante mis estudios o por mi cuenta para ampliar mis habilidades. No se incluyen proyectos de mi vida profesional por cuestiones de confidencialidad.

<p class="annot">Se recomienda abrir los informes en una pestaña nueva</p>

## Proyectos académicos

### Trabajo de fin de grado: Minería de textos

Realicé mi TFG sobre el **análisis bibliométrico en psicología**, obteniendo en el mismo la máxima calificación. El objetivo del proyecto era estudiar la evolución de la investigación en psicología a partir de los datos disponibles de forma libre en [Scopus](https://www.scopus.com/), una base de datos de artículos científicos.

Para ello, en primer lugar tenía que descargar los artículos de la base de datos, lo que implicaba interactuar con la API. Ésta tarea la desarrollé en **python**, ya que ofrece más facilidades para capturar excepciones y errores. Además, python tiene mejor soporte para trabajar con ficheros json ya que uno de sus tipos nativos (el diccionario) se ajusta muy bien a ésta estructura de datos.

Los datos se almacenaban en una base de datos de **SQLite**, que resultó ser perfecta para el proyecto.

El análisis de los datos lo realicé con **R**, presentando los resultados en un informe de R markdown. Realicé un análisis descriptivo muy completo mediante **gráficos interactivos**, además probé varias técnicas de clusterización para ver si se podían realizar clasificaciones de los artículos de forma automática. También, desarrollé un método que a partir de unas métricas de similaridad permite crear redes temáticas.

[Informe](projects/TFG_MineriaTextoCompleto.html)

### Práctica TCT

Una práctica del máster sobre la Teoría Clásica de los Tests.

[Informe en PDF](projects/TCT.pdf)

## Proyectos personales

### Informe de ventas Target

Utilicé unos datos ficticios para crear un informe de Ventas con estética de la marca Target. Todos los elementos del informe utilizan los colores de la marca, incluidos los gráficos de **ggplot**.

[Informe](projects/VentasTarget.html), [Código](https://github.com/manu-torres/portfolio/blob/main/projects/VentasTarget.Rmd)

### Comunicado para accionistas LVMH

En la página del grupo Louis Vuitton encontré un comunicado para accionistas, y me gustó la estética de la página. Por tanto, intenté replicar la estética del documento utilizando **HTML** y **CSS**.

[Informe](projects/ComunicadoLVMH.html), [Código](https://github.com/manu-torres/portfolio/blob/main/projects/ComunicadoLVMH.Rmd)

### Bolsa

En un principio simplemente estaba buscando un tutorial para aprender a utilizar redes neuronales de tipo LSTM, y en el ejemplo utilizaban éstos modelos para predecir el precio de unas acciones. Desde entonces, he estado investigando bastante sobre el tema ya que es un problema muy interesante.

He construido un sistema que va descargando automáticamente los precios y datos financieros de **más de 500 empresas** e incorpora toda ésta información en una base de datos de **SQLite**. Una vez que los datos están descargados, utilizo **R** y **python** para realizar toda clase de análisis y simulaciones sobre los mismos.

A continuación podemos ver algunos de los proyectos relacionados con éste tema.

#### Generación de cuadros de mando

Hay muchas páginas que permiten consultar la información financiera de las acciones, pero yo he creado un sistema que me permite generar mis propios informes personalizados. Utilizando la librería **flexdashboard** he creado unos cuadros de mando interactivos que recogen todo tipo de información sobre las acciones.

Se le puede especificar el código de una empresa, y un script descarga los datos más recientes para esa empresa y construye el cuadro de mando. En el mismo, podemos ver entre otras cosas un gráfico con las bandas de Bollinger, gráficos de velas o información sobre el pago de dividendos.

[Informe](projects/DashboardAccion.html), [Código](https://github.com/manu-torres/portfolio/blob/main/projects/DashboardAccion.Rmd)

<br>

<br>
